name: point_maze_medium
save_name: medium
args: []
kwargs: {}

dataset:
  _target_: "datasets.point_maze_dset.load_point_maze_slice_train_val"
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/point_maze_medium
  split_ratio: 0.9
  use_preprocessed: false
  use_frame_files: false
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 16
